#! /bin/sh

python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_50_V1_V2_V3_V4_baseline.csv PPTERM 91 OFA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_50_V1_V2_V3_V4_baseline.csv PPTERM 91 CLA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_50_V1_V2_V3_V4_baseline.csv PPTERM 91 WMA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_50_V1_V2_V3_V4_baseline.csv PPTERM 91 CAA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_60_V1_V2_V3_V4_baseline.csv PPTERM 91 OFA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_60_V1_V2_V3_V4_baseline.csv PPTERM 91 CLA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_60_V1_V2_V3_V4_baseline.csv PPTERM 91 WMA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_60_V1_V2_V3_V4_baseline.csv PPTERM 91 CAA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_70_V1_V2_V3_V4_baseline.csv PPTERM 91 OFA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_70_V1_V2_V3_V4_baseline.csv PPTERM 91 CLA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_70_V1_V2_V3_V4_baseline.csv PPTERM 91 WMA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_70_V1_V2_V3_V4_baseline.csv PPTERM 91 CAA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_80_V1_V2_V3_V4_baseline.csv PPTERM 91 OFA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_80_V1_V2_V3_V4_baseline.csv PPTERM 91 CLA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_80_V1_V2_V3_V4_baseline.csv PPTERM 91 WMA 20
python TreeEnsemble.py data_preprocessing/protect_data_no_prefill_80_V1_V2_V3_V4_baseline.csv PPTERM 91 CAA 20
